image:
  file: .gitpod.Dockerfile
ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-preview
tasks:
  - init: |
      git submodule update --init --recursive
      ./gradlew build
    command: ./gradlew run
