---
# This workflow will build a Java project with Gradle
# For more information see:
# https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle
name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        jdk: [11]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Set up JDK ${{ matrix.jdk }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.jdk }}
    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Upload jars as artifact
      uses: actions/upload-artifact@v2
      with:
        name: software-challenge-gui-${{ matrix.os }}-${{ github.sha }}
        path: build/distributions/*zip
      continue-on-error: true
    - name: Execute tests
      run: ./gradlew test
